# docker compose down && docker compose up -d --build
services:
  sparkify.proxy:
    container_name: sparkify.proxy
    ports:
      - 443:443
      - 80:80
    networks:
      - sparkify
    build:
      context: .
      dockerfile: ./Sparkify.Proxy/Dockerfile

  sparkify:
    container_name: sparkify
    ports:
      - 6001:8080
    networks:
      - sparkify
    build:
      context: .
      dockerfile: ./Sparkify/Dockerfile
      
  # see: https://developers.eventstore.com/server/v20.10/installation.html#use-docker-compose
  eventstore.db:
    image: eventstore/eventstore:latest
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=false
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=false
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore

networks:
  sparkify:
    # TODO: remove external?
    name: sparkify 
    external: true
  eventstore-volume-data:
  eventstore-volume-logs: